name: Test(Cargo)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # For a given workflow, if we push to the same PR, cancel all previous builds on that PR.
  # If the push is not attached to a PR, we will cancel all builds on the same branch.
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake catch2

      # - name: Setup cmake
      #   uses: jwlawson/actions-setup-cmake@v2
      #   with:
      #     cmake-version: '3.16.x'
      - name: Use cmake
        run: cmake ./tests/cpp

      - name: Use cmake
        run: cmake --build ./tests/cpp

      - uses: actions-rs/cargo@v1
        with:
          command: test



  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features