name: Test(Cargo)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # For a given workflow, if we push to the same PR, cancel all previous builds on that PR.
  # If the push is not attached to a PR, we will cancel all builds on the same branch.
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    env:
      GENERATED_DIRECTORY: /workspaces/ramble/generated/
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Generate C++ Ramble files
        run: ./target/release/ramble generate  --C -o "$GENERATED_DIRECTORY"

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake catch2

      - name: Configure Cmake
        working-directory: ./tests/cpp
        run: cmake . 

      - name: Build with Cmake
        working-directory: ./tests/cpp
        run: cmake --build . -v

      - name: Run tests with Catch2
        run: ./tests/cpp/run_tests.sh "$GENERATED_DIRECTORY"


  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features