name: Target(Rust)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # For a given workflow, if we push to the same PR, cancel all previous builds on that PR.
  # If the push is not attached to a PR, we will cancel all builds on the same branch.
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  tests_rust:
    name: Test(Cargo)
    runs-on: ubuntu-latest
    env:
      RAMBLE_GENERATED_DIRECTORY: ./tests/rust/src

    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: ./tests/rust/run_gen_tests.sh ./tests/ramble.yaml
